db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: ampcrowd
    POSTGRES_USER: ampcrowd
rabbitmq:
  image: rabbitmq
web:
  build: .
  links:
    - db
    - rabbitmq
  ports:
    - "8000:8000"
  volumes:
    - .:/usr/src/app
